# Generated by Django 2.1.15 on 2020-08-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iglesias',
            options={'managed': True},
        ),
    ]
