# Generated by Django 2.1.15 on 2020-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_auto_20200822_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesias',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
