# Generated by Django 2.1.15 on 2020-08-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0003_iglesias_activa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obreros',
            options={'managed': True},
        ),
    ]
