# Generated by Django 2.1.15 on 2020-08-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0004_auto_20200822_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obreros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='obreros',
            name='iglesia_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.Iglesias'),
        ),
    ]
