# Generated by Django 2.1.15 on 2020-08-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_auto_20200822_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iglesias',
            options={'managed': True, 'verbose_name_plural': 'Iglesias'},
        ),
        migrations.AlterModelOptions(
            name='obreros',
            options={'managed': True, 'verbose_name_plural': 'Pastores y obreros'},
        ),
    ]
