# Generated by Django 2.1.15 on 2020-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0006_auto_20200822_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aportesiglesias',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='anios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
