# Generated by Django 2.1.15 on 2020-08-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0007_auto_20200822_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportesiglesias',
            name='anio_id',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.Anios'),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='iglesia_id',
            field=models.ForeignKey(default=849, on_delete=django.db.models.deletion.CASCADE, to='tesoreria.Iglesias', verbose_name='Iglesia que aporta'),
        ),
    ]
