# Generated by Django 2.1.15 on 2020-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0008_auto_20200822_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportesiglesias',
            name='abr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='ago',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='dic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='ene',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='feb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='jul',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='jun',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='mar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='may',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='nov',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='oct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesiglesias',
            name='sep',
            field=models.FloatField(default=0.0),
        ),
    ]
