# Generated by Django 2.1.15 on 2020-08-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0009_auto_20200822_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aportesobreros',
            options={'managed': True},
        ),
    ]
