# Generated by Django 2.1.15 on 2020-08-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0010_auto_20200822_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportesobreros',
            name='abr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='ago',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='anio_id',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.DO_NOTHING, to='tesoreria.Anios'),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='dic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='ene',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='feb',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='jul',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='jun',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='mar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='may',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='nov',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='obrero_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tesoreria.Obreros', verbose_name='Obrero que aporta'),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='oct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aportesobreros',
            name='sep',
            field=models.FloatField(default=0.0),
        ),
    ]
