# Generated by Django 2.1.15 on 2020-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0011_auto_20200822_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesias',
            name='misioneros',
            field=models.ManyToManyField(blank=True, to='tesoreria.Obreros'),
        ),
        migrations.RemoveField(
            model_name='obreros',
            name='iglesia_id',
        ),
        migrations.AddField(
            model_name='obreros',
            name='iglesia_id',
            field=models.ManyToManyField(blank=True, to='tesoreria.Iglesias'),
        ),
    ]
