# Generated by Django 2.1.15 on 2020-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0012_auto_20200822_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='obreros',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
