# Generated by Django 2.1.15 on 2020-08-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0014_auto_20200822_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglesias',
            name='alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='iglesia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='presbiterio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='provincia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='obreros',
            name='alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obreros',
            name='baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obreros',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obreros',
            name='nombre',
            field=models.CharField(blank=True, db_column='Nombre', max_length=200, null=True),
        ),
    ]
