# Generated by Django 2.1.15 on 2020-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0015_auto_20200822_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglesias',
            name='iglesia',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='presbiterio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='provincia',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
