# Generated by Django 2.1.15 on 2020-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0015_auto_20200822_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obreros',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
