# Generated by Django 2.1.15 on 2020-08-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0016_auto_20200822_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportesobreros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='iglesia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='presbiterio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='provincia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
