# Generated by Django 2.1.15 on 2020-08-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0018_auto_20200826_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='obreros',
            name='foto',
            field=models.ImageField(blank=True, default='static/assets/img/theme/team-1-800x800.jpg', null=True, upload_to='tesoreria/avatars'),
        ),
    ]
