# Generated by Django 3.0.8 on 2020-08-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='simple_select', max_length=200, verbose_name='tipo de pregunta'),
        ),
    ]
