# Generated by Django 3.0.8 on 2020-08-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
