# Generated by Django 2.1.15 on 2020-08-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_auto_20200817_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/assets/img/theme/team-1-800x800.jpg', null=True, upload_to='encuestas/avatars'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='static/assets/img/theme/profile-cover.jpg', null=True, upload_to='encuestas/avatars_bg'),
        ),
    ]
