# Generated by Django 2.1.15 on 2020-08-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0008_auto_20200817_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='personas',
            field=models.ManyToManyField(blank=True, to='encuestas.Persona'),
        ),
    ]
