# Generated by Django 2.1.15 on 2020-08-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0009_curso_personas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='personas',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='courses',
        ),
    ]
