# Generated by Django 2.1.15 on 2020-08-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0010_auto_20200821_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='personas',
            field=models.ManyToManyField(blank=True, to='encuestas.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='courses',
            field=models.ManyToManyField(blank=True, to='encuestas.Curso'),
        ),
    ]
