# Generated by Django 2.1.15 on 2020-08-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0011_auto_20200821_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='year',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
